In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('preprocessing data.csv')

In [3]:
data.isnull().sum()

A    3
B    3
C    4
D    3
E    4
F    2
G    4
H    4
dtype: int64

In [4]:
data.fillna(data.median(numeric_only=True).round(1), inplace=True)
pd.DataFrame(data)

A        B    C      D      E      F     G       H
0  23.0   8000.0  1.1   23.0  555.0    Red  Yes     Male
1  32.0   5000.0  2.1   26.0  555.5   Blue    No    Male
2  46.0   6000.0  2.4  125.0  555.5  Black  Yes      NaN
3  54.0  70000.0  2.4  140.0  555.5    Red   NaN     NaN
4  64.0   6500.0  3.6   24.0  574.0    NaN    No    Male
5  46.0   6000.0  2.5   26.0  556.0    Red   NaN  Female
6  46.0   6000.0  2.4   26.0  545.0   Blue   NaN    Male
7  53.0   4500.0  2.4   26.0  586.0    Red  Yes      NaN
8  46.0   6000.0  4.2   26.0  555.5  Black  Yes     Male
9  24.0   3200.0  2.3   25.0  546.0    NaN   NaN     NaN

In [5]:
data

A        B    C      D      E      F     G       H
0  23.0   8000.0  1.1   23.0  555.0    Red  Yes     Male
1  32.0   5000.0  2.1   26.0  555.5   Blue    No    Male
2  46.0   6000.0  2.4  125.0  555.5  Black  Yes      NaN
3  54.0  70000.0  2.4  140.0  555.5    Red   NaN     NaN
4  64.0   6500.0  3.6   24.0  574.0    NaN    No    Male
5  46.0   6000.0  2.5   26.0  556.0    Red   NaN  Female
6  46.0   6000.0  2.4   26.0  545.0   Blue   NaN    Male
7  53.0   4500.0  2.4   26.0  586.0    Red  Yes      NaN
8  46.0   6000.0  4.2   26.0  555.5  Black  Yes     Male
9  24.0   3200.0  2.3   25.0  546.0    NaN   NaN     NaN

In [6]:
# data["A_median"]= data["A"].fillna(data['A'].mean())
# data

In [7]:
# data=data.fillna(data['A'].mean())
# data

In [8]:
data['F'].mode()[0]

'Red'

In [9]:
data['F'].isnull().sum()

2

In [10]:
random_sample=data['F'].dropna().sample(2,random_state=1)
random_sample

8    Black
2    Black
Name: F, dtype: object

In [11]:
random_sample.index=data[data['F'].isnull()].index
random_sample

4    Black
9    Black
Name: F, dtype: object

In [12]:
data['F']=data["F"].fillna(random_sample)
data

A        B    C      D      E      F     G       H
0  23.0   8000.0  1.1   23.0  555.0    Red  Yes     Male
1  32.0   5000.0  2.1   26.0  555.5   Blue    No    Male
2  46.0   6000.0  2.4  125.0  555.5  Black  Yes      NaN
3  54.0  70000.0  2.4  140.0  555.5    Red   NaN     NaN
4  64.0   6500.0  3.6   24.0  574.0  Black    No    Male
5  46.0   6000.0  2.5   26.0  556.0    Red   NaN  Female
6  46.0   6000.0  2.4   26.0  545.0   Blue   NaN    Male
7  53.0   4500.0  2.4   26.0  586.0    Red  Yes      NaN
8  46.0   6000.0  4.2   26.0  555.5  Black  Yes     Male
9  24.0   3200.0  2.3   25.0  546.0  Black   NaN     NaN

In [13]:
data.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='object')

In [14]:
print(data['F'])

0      Red
1     Blue
2    Black
3      Red
4    Black
5      Red
6     Blue
7      Red
8    Black
9    Black
Name: F, dtype: object


In [15]:
from sklearn.preprocessing import MinMaxScaler,RobustScaler,StandardScaler
data = [[-1,6],[100,2],[300,200]]
data

[[-1, 6], [100, 2], [300, 200]]

In [16]:
mx = MinMaxScaler()
mx.fit_transform(data)

array([[0.        , 0.02020202],
       [0.33554817, 0.        ],
       [1.        , 1.        ]])

In [17]:
rs = RobustScaler()
rs.fit_transform(data)

array([[-0.67109635,  0.        ],
       [ 0.        , -0.04040404],
       [ 1.32890365,  1.95959596]])

In [18]:
ss = StandardScaler()
ss.fit_transform(data)

array([[-1.07132599, -0.68535362],
       [-0.26383401, -0.72863911],
       [ 1.33516   ,  1.41399274]])